function [x,cost] = optimizeAll(filename)
studTable = readtable(filename, 'Sheet', 'Students');
rewardTable = readtable(filename, 'Sheet', 'Reward');
requirements = xlsread(filename, 3);
[f,A,b,Aeq,beq,staffNumberVector] = makeMILPMatricesStuds(studTable,rewardTable,requirements);
nVars=numel(f);
lb = zeros(nVars,1);
ub = ones(nVars,1);
[x,cost] = intlinprog(-f,1:nVars,A,b,Aeq,beq,lb,ub);